config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pokedexes
  resources :skills
  resources :pokemons do
    post 'heal'
    get 'heal_all', on: :collection
  	resources :pokemon_skills
  end
  resources :pokemon_battles do
    resources :pokemon_battle_logs
    get 'auto_battle'
  	post 'attack'
  	post 'surrender'
  end
  root 'pages#home'
end

app/models/skill.rb
class Skill < ApplicationRecord
	ELEMENT = [
			'normal',
			'fighting',
			'flying',
			'poison',
			'ground',
			'rock',
			'bug',
			'ghost',
			'steel',
			'fire',
			'water',
			'grass',
			'electro',
			'psychic',
			'ice',
			'dragon',
			'dark',
			'fairy'
		]

	has_many :pokemon_skills, dependent: :destroy
	validates :name, 
		presence: true, 
		length: {maximum: 45}, 
		uniqueness: true
	validates :power, 
		numericality: {only_integer: true, greater_than: 0}
	validates :max_pp, 
		numericality: {only_integer: true, greater_than: 0} 
	validates :element_type, 
		presence: true, 
		length: {maximum: 45}, 
		inclusion: { in: ELEMENT }
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
	
	def index
		@skills = Skill.all

		@element_type = []
		Skill::ELEMENT.each do |element|
			skill_award = SkillAward.new(element_type: element)
			h = {}
			h[:element] = element
			h[:best_skills] = skill_award.most_used_skill
			h[:all_skills] = skill_award.all_normal_skill
			@element_type << h
		end 

		navigation_add("Skill Index", "#")
	end

	def new
		@skill = Skill.new
		navigation_add("Skill Index", skills_path)
		navigation_add("New Skill", "#")
	end

	def create
		@skill = Skill.new(skill_params)
		if @skill.valid?
			@skill.save
			redirect_to @skill
		else
			render 'new'
		end
	end

	def edit
		@skill = Skill.find(params[:id])	
		navigation_add("Skill Index", skills_path)
		navigation_add("Skill Show", @skill)
		navigation_add("Edit Skill", "#")
	end

	def update
		@skill = Skill.find(params[:id])
		@skill.update(skill_params)
		if @skill.valid?
			@skill.save
			redirect_to @skill
		else
			render 'edit'
		end
	end

	def show
		@skill = Skill.find(params[:id])
		navigation_add("Skill Index", skills_path)
		navigation_add("Skill Show", "#")
	end

	def destroy
		@skill = Skill.find(params[:id])
		name = @skill.name
		@skill.destroy
		flash[:notice] = "#{name} removed."
		redirect_to skills_path
	end

	private
	def skill_params
		params.require(:skill).permit(
			:name,
			:power,
			:max_pp,
			:element_type
			)
	end

end

app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
	<%= f.label 'Name', for: 'name' %>
	<%= f.text_field :name, placeholder: 'Name', class: 'form-control form-group' %>
	
	<%= (content_tag(:div, @skill.errors.full_messages_for(:name).to_sentence , class: 'alert alert-danger', role: 'alert')) if @skill.errors.include?(:name) %>
	
	<%= f.label 'Power', for: 'power' %>
	<%= f.number_field :power, placeholder: 'Power', class: 'form-control form-group' %>

	<%= (content_tag(:div, @skill.errors.full_messages_for(:power).to_sentence , class: 'alert alert-danger', role: 'alert')) if @skill.errors.include?(:power) %>

	<%= f.label 'Max PP', for: 'max_pp' %>
	<%= f.number_field :max_pp, placeholder: 'Max PP', class: 'form-control form-group' %>

	<%= (content_tag(:div, @skill.errors.full_messages_for(:max_pp).to_sentence , class: 'alert alert-danger', role: 'alert')) if @skill.errors.include?(:max_pp) %>

	<%= f.label 'Element Type', for: 'element_type' %>
	<%= f.select(:element_type, Skill::ELEMENT, {}, {class: 'form-control form-group'}) %>

	<%= f.submit "Submit", class: "btn btn-primary form-group" %>
<% end %>

app/views/skills/edit.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>Edit Skill</h1>
	</div>
<% end %>

<div class="col-sm-12">
	<%= render 'form' %>
</div>

app/views/skills/index.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>Skill</h1>
	</div>	
<% end %>

<div class="col-sm-12 grass-title">
	<%= link_to "+ New Skill", new_skill_path, class: 'btn btn-primary' %>
	<ul class="nav nav-pills" role="tablist">
		<% Skill::ELEMENT.each do |element| %>
			<li><a role="presentation" data-toggle="tab" href="#<%= element %>"><%= "#{element}" %></a></li>
		<% end %>
	</ul>
</div>

<div class="col-sm-12 tab-content">
	<% @element_type.each do |element| %>
		<div role="tab-panel" id="<%= element[:element] %>" class="tab-pane">

		<div class="col-sm-12 grass-title">
			<h1>Highest Pokedex Level</h1>
			<% idx = 0 %>
			<% element[:best_skills].each do |skill| %>
			<div class="col-sm-4">
				<table class="table table-bordered well">
					<tr class="red">
						<td colspan="2"><h1><center><%= idx+=1 %></center></h1></td>
					</tr>
					<tr>
						<td class="grass" width="50%">Name</td>
						<td class="grass-sub"><kbd><%= skill[:skill].name %></kbd></td>
					</tr>
					<tr>
						<td class="grass">Times used</td>
						<td class="grass-sub"><%= skill[:count] %> </td>
					</tr>
					</table>
				</div>
			<% end %>
		</div>

		<div class="col-sm-12 grass-title">
				<h1>All Skills</h1>
				<% idx = 0 %>
				<% element[:all_skills].each do |skill| %>
					<div class="col-sm-4">
						<table class="table table-bordered well">
							<tr class="red">
								<td colspan="2"><h1><center><%= idx+=1 %></center></h1></td>
							</tr>
							<tr>
								<td class="grass" width="50%">Name</td>
								<td class="grass-sub"><kbd><%= skill[:skill].name %></kbd></td>
							</tr>
							<tr>
								<td class="grass">Power</td>
								<td class="grass-sub"><%= skill[:skill].power %> </td>
							</tr>
							<tr>
								<td class="grass">Max PP</td>
								<td class="grass-sub"><%= skill[:skill].max_pp %> </td>
							</tr>
							<tr>
								<td class="grass-sub" colspan="2">
									<ul class="list-inline">
										<li>
											<%= link_to "Show", skill[:skill], class: 'btn btn-primary' %>
										</li>
										<li><%= link_to "Edit", edit_skill_path(skill[:skill]), class: 'btn btn-warning' %></li>
										<li><%= button_to 'Delete', skill_path(skill[:skill]) , method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></li>
									</ul>
								</td>
							</tr>
						</table>
					</div>
				<% end %>
			</div>

		</div>
	<% end %>
</div>

app/views/skills/new.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>New Skill</h1>
	</div>
<% end %>
<div class="col-sm-12">
	<%= render 'form' %>
</div>

app/views/skills/show.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>Skill Show</h1>
	</div>
<% end %>

<div class="col-sm-6">
<ul class="list-inline">
	<li><%= link_to 'Edit', edit_skill_path(@skill), class: 'btn btn-primary' %></li>
	<li><%= button_to 'Delete', @skill, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %></li>
</ul>
<table class="table table-inverse">
	<tr>
		<td class="bg-primary" width="50%">#</td>
		<td><%= @skill.id %></td>
	</tr>
	<tr>
		<td class="bg-primary">Name</td>
		<td><%= @skill.name %></td>
	</tr>
	<tr>
		<td class="bg-primary">Power</td>
		<td><%= @skill.power %></td>
	</tr>
	<tr>
		<td class="bg-primary">Max PP</td>
		<td><%= @skill.max_pp %></td>
	</tr>
	<tr>
		<td class="bg-primary">Element Type</td>
		<td><%= @skill.element_type %></td>
	</tr>
</table>
</div>