config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pokedexes
  resources :skills
  resources :pokemons do
    post 'heal'
    get 'heal_all', on: :collection
  	resources :pokemon_skills
  end
  resources :pokemon_battles do
    resources :pokemon_battle_logs
    get 'auto_battle'
  	post 'attack'
  	post 'surrender'
  end
  root 'pages#home'
end

app/models/pokemon_battle.rb
class PokemonBattle < ApplicationRecord
	STATE = ['Ongoing', 'Finished']
	BATTLE_TYPE = [
		"Me vs Me",
		"Me vs AI", 
		"AutoMatch!"]

	belongs_to :pokemon1, class_name: 'Pokemon'
	belongs_to :pokemon2, class_name: 'Pokemon'
	has_many :pokemon_battle_logs, dependent: :destroy
	validates :pokemon1_id, presence: true
	validates :pokemon2_id, presence: true
	validates :pokemon1_max_health_point, 
		presence: true, 
		numericality: {
			only_integer: true, greater_than: 0}
	validates :pokemon2_max_health_point, 
		presence: true, 
		numericality: {
			only_integer: true, greater_than: 0}
	validates :battle_type, presence: true, inclusion: {in: BATTLE_TYPE}
	validates :state, presence: true, inclusion: {in: STATE}
	validates :current_turn, presence: true, numericality: { only_integer: true, greater_than: 0}
	validate :check_pokemon1_and_pokemon2
	validate :check_pokemon_hp_zero

	def check_pokemon_hp_zero
		@list_pokemons = []
		Pokemon.all.each { |poke| @list_pokemons << poke if poke.current_health_point > 0 }
		if self.state == "Ongoing"
			if @list_pokemons.exclude? pokemon1
				errors.add(:pokemon1_id, "Cannot add Pokemon with empty HP.")
			elsif @list_pokemons.exclude? pokemon2
				errors.add(:pokemon2_id, "Cannot add Pokemon with empty HP.")
			end
		end
	end

	def check_pokemon1_and_pokemon2
		if self.pokemon2_id == self.pokemon1_id
			errors.add(:pokemon1_id, "Cannot be the same pokemon.")
			errors.add(:pokemon2_id, "Cannot be the same pokemon.")
		end
	end

	def pokemon1_name
		pokemon1.name
	end

	def pokemon2_name
		pokemon2.name
	end

	def pokemon1_image
		pokemon1.pokedex_image
	end

	def pokemon2_image
		pokemon2.pokedex_image
	end
end

app/controllers/pokemon_battles_controller.rb
class PokemonBattlesController < ApplicationController
	def index
		@pokemon_battles = PokemonBattle.all
		navigation_add("Pokemon Battle Index", "#")
	end

	def new
		@pokemon_battle = PokemonBattle.new
		@list_pokemons = []
		Pokemon.all.each { |poke| @list_pokemons << [poke.name, poke.id] if poke.current_health_point > 0 }
		@list_battle_types = []
		PokemonBattle::BATTLE_TYPE.each { |type| @list_battle_types << [type, type]}
		navigation_add("Pokemon Battle Index", pokemon_battles_path)
		navigation_add("Pokemon Battle New", "#")
	end

	def create
		@pokemon_battle = PokemonBattle.new(pokemon_battle_params)
		get_each_pokemon
		set_pokemon_battle_attr
		if @pokemon_battle.valid?
			@pokemon_battle.save
			if @pokemon_battle.battle_type == "AutoMatch!"
				redirect_to pokemon_battle_auto_battle_path(@pokemon_battle)
			else
				redirect_to @pokemon_battle
			end
		else
			@list_pokemons = []
			Pokemon.all.each { |poke| @list_pokemons << [poke.name, poke.id] if poke.current_health_point > 0 }
			@list_battle_types = []
			PokemonBattle::BATTLE_TYPE.each { |type| @list_battle_types << [type, type]}			
			render 'new'
		end
	end

	def destroy
		@pokemon_battle = PokemonBattle.find(params[:id])
		@pokemon_battle.destroy
		redirect_to pokemon_battles_path
	end

	def show
		@pokemon_battle = PokemonBattle.find(params[:id])
		@pokemon_battle_logs = @pokemon_battle.pokemon_battle_logs.sort_by { |h| h[:turn]}
		get_each_pokemon
		navigation_add("Pokemon Battle Index", pokemon_battles_path)
		navigation_add("Pokemon Battle Show", "#")
	end

	def attack
		@pokemon_battle = PokemonBattle.find(params[:pokemon_battle_id])
		if @pokemon_battle.battle_type == "Me vs Me"
			manual_attack
		elsif @pokemon_battle.battle_type == "Me vs AI"
			ai_attack
		end
	end

	def auto_battle
		@pokemon_battle = PokemonBattle.find(params[:pokemon_battle_id])
		pokemon_battle_auto_engine = PokemonBattleAutoEngine.new(pokemon_battle: @pokemon_battle)
		pokemon_battle_auto_engine.begin_auto_battle
		redirect_to @pokemon_battle
	end

	def surrender
		@pokemon_battle = PokemonBattle.find(params[:pokemon_battle_id])
		manual_surrender
	end

	private
	
	def manual_attack
		pokemon_battle_engine = PokemonBattleEngine.new(
			pokemon_battle: @pokemon_battle, 
			attacker_id: params[:attacker_id], 
			skill_id: params[:skill_id])
		if pokemon_battle_engine.list_attack_validations?
			pokemon_battle_engine.attack
			pokemon_battle_engine.save_attack
			redirect_to @pokemon_battle
		else
			get_each_pokemon
			render 'show'
		end
	end

	def ai_attack
		pokemon_battle_engine = PokemonBattleEngine.new(
			pokemon_battle: @pokemon_battle,
			attacker_id: @pokemon_battle.pokemon1_id,
			skill_id: params[:skill_id])
		if pokemon_battle_engine.list_attack_validations?
			pokemon_battle_engine.attack
			pokemon_battle_engine.save_attack

			pokemon_battle_ai_engine = PokemonBattleAiEngine.new(
				pokemon_battle: @pokemon_battle)
			
			pokemon_battle_ai_engine.begin_ai_battle
			redirect_to @pokemon_battle
		else
			get_each_pokemon
			render 'show'
		end
	end

	def manual_surrender
		pokemon_battle_engine = PokemonBattleEngine.new(
			pokemon_battle: @pokemon_battle,
			attacker_id: params[:surrender_id])
		if pokemon_battle_engine.list_surrender_validations?
			pokemon_battle_engine.surrender
			pokemon_battle_engine.save_surrender
			redirect_to @pokemon_battle
		else
			get_each_pokemon
			render 'show'	
		end
	end

	def pokemon_battle_params
		params.require(:pokemon_battle).permit(
									 :pokemon1_id, 
									 :pokemon2_id,
									 :battle_type)
	end

	def set_pokemon_battle_attr
		@pokemon_battle.current_turn = 1
		@pokemon_battle.state = "Ongoing"
		@pokemon_battle.pokemon1_max_health_point = @pokemon1.max_health_point
		@pokemon_battle.pokemon2_max_health_point = @pokemon2.max_health_point
	end

	def get_each_pokemon
		@pokemon1 = Pokemon.find(@pokemon_battle.pokemon1_id)
		@pokemon2 = Pokemon.find(@pokemon_battle.pokemon2_id)
	end

end

app/views/pokemon_battles/index.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>Pokemon Battle</h1>
	</div>
<% end %>

<div class="col-sm-12">
	<%= link_to '+ New Pokemon Battle', new_pokemon_battle_path, class: "btn btn-primary"%>
	<br /><br />
	<table class="table table-bordered">
		<thead>
		  <tr class="bg-primary">
		    <th width="50%">Pokemon 1</th>
		    <th width="50%"  style="text-align: right;">Pokemon 2</th>
		  </tr>
		</thead>
	</table>

	<% if !@pokemon_battles.nil? %>
		<% idx = 0 %>
		<% pokemon_battles = @pokemon_battles.sort { |a,b| b <=> a} %>
		<% pokemon_battles.each do |pokemon_battle| %>
			<table class="table table-bordered">
				<tr class="well">
					<td style="text-align: center;" colspan="2">
						<ul class="list-inline">
							<li><a class="btn btn-default"><%= pokemon_battle.updated_at.strftime("%c") %></a></li>
							<li><a class="btn btn-default">Turn: <%= pokemon_battle.current_turn %></a></li>
							<li><a class="btn btn-default">State: <%= pokemon_battle.state %></a></li>
							<li>
								<a class="btn btn-default"><%= pokemon_battle.battle_type %></a>
							</li>
							<li><%= link_to "Battle! ⚔", pokemon_battle, class: 'btn btn-success' %></li>
							<li><%= button_to 'Destroy', pokemon_battle, 
								method: :delete,
								class: 'btn btn-danger',
					  data: { confirm: 'Are you sure?' } %></li>
					  		<li><%= link_to "Battle Logs", pokemon_battle_pokemon_battle_logs_path(pokemon_battle_id: pokemon_battle), class: 'btn btn-warning' %></li>
					  </ul>	
					</td>
				</tr>
				<tr class="bg-default">
					<td width="40%" class="red">
						<%= image_tag pokemon_battle.pokemon1_image, size: "350x350" %><br />
						<h1><kbd><%= pokemon_battle.pokemon1_name %></kbd></h1>
					</td>
				  <td style="text-align: right;"  width="40%"  class="blue"><%= image_tag pokemon_battle.pokemon2_image, size: "350x350" %><br /><h1><kbd><%= pokemon_battle.pokemon2_name %></kbd></h1>
				  </td>
				</tr>	
			</table>
		<% end %>
	<% end %>
</div>

app/views/pokemon_battles/new.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>Select Pokemon</h1>
	</div>
<% end %>

<%= form_for @pokemon_battle do |f| %>
	<div class="col-sm-5 red">
		<%= f.label 'Select Pokemon 1', for: 'pokemon1_id' %>
		<%= f.select(:pokemon1_id, @list_pokemons, {}, {class: 'form-control form-group'}) %>
		<%= (content_tag(:div, @pokemon_battle.errors.full_messages_for(:pokemon1_id).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon_battle.errors.include?(:pokemon1_id) %>
	</div>
	<div class="col-sm-2">
		<center>
			<%= image_tag 'vs_image.png', size: "100x100"%>
			<%= f.select(:battle_type, @list_battle_types, {}, {class: 'form-control form-group'})%>
			<%= f.submit 'Battle!', class: 'btn btn-warning'%>
		</center>
	</div>
	<div class="col-sm-5 blue">
		<%= f.label 'Select Pokemon 2', for: 'pokemon2_id' %>
		<%= f.select(:pokemon2_id, @list_pokemons, {}, {class: 'form-control form-group'}) %>
		<%= (content_tag(:div, @pokemon_battle.errors.full_messages_for(:pokemon2_id).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon_battle.errors.include?(:pokemon2_id) %>
	</div>
<% end %>

app/views/pokemon_battles/show.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>Pokemon Battle Show</h1>
		<p> <%= @pokemon_battle.battle_type %></p>
	</div>
<% end %>

<div class="col-sm-12" id="versus">
	<%= image_tag "vs_image.png", size: "200x200"%>
	<%= (content_tag(:div, @pokemon_battle.errors.full_messages.to_sentence , class: 'alert alert-danger', role: 'alert')) unless @pokemon_battle.errors.empty? %>
	<h1 class="turn"><kbd><%= "#{@pokemon_battle.current_turn}" %></kbd></h1>
</div>
<div class="col-sm-6" id="pokemon1">
	<h1><% if @pokemon_battle.pokemon_winner_id == @pokemon1.id and @pokemon_battle.state == "Finished" %>
		<kbd><%= "WINNER" %></kbd>
	<% elsif @pokemon_battle.state == "Finished" %>
		<kbd><%= "LOSER" %></kbd>
	<% end %></h1>
	<pre>Pokemon 1</pre>
	<%= image_tag @pokemon1.pokedex_image, size: "300x300" %>
	<br /><br />
	<table class="table table-bordered">
		<tr>
			<td class="bg-primary" width="50%">Name</td>
			<th class="bg-primary"><%= @pokemon1.name %></th>
		</tr>
		<tr>
			<td class="bg-primary">HP</td>
			<th class="bg-primary"><%= @pokemon1.current_health_point %>
				/
				<%= @pokemon1.max_health_point %>
			</th>
		</tr>
	</table>
	<% unless @pokemon_battle.state == "Finished" %>
	<table class="table table-bordered">
		<tr>
			<td class="bg-primary">Skills</td>
			<th class="bg-primary">
				<%= form_tag(pokemon_battle_attack_path(@pokemon_battle), method: 'post') do %>
					<select class="form-control form-group" name="skill_id">
						<% @pokemon1.pokemon_skills.each do |pokemon_skill| %>
							<option value="<%= pokemon_skill.id %>">
								<%= "#{pokemon_skill.skill_name} (#{pokemon_skill.current_pp}/#{pokemon_skill.skill_max_pp})" %>
								</option>
						<% end %>
					</select>
					<input type="hidden" name="attacker_id" value="<%= @pokemon1.id %>">
			</th>
		</tr>
		<tr>
			<td colspan="2">	
				<ul class="list-inline">
					<li><%= submit_tag "Attack", class: 'btn btn-danger' %></li>
					<% end %>
					<li>
						<%= form_tag(pokemon_battle_surrender_path(@pokemon_battle), method: 'post') do %>
						<%= submit_tag "Surrender", class: 'btn btn-warning' %>
						<input type="hidden" name="surrender_id" value="<%= @pokemon1.id %>">
						<% end %>
					</li>
					<li><%= (content_tag(:div, @pokemon_battle.errors.full_messages_for(:pokemon1_id).to_sentence , class: 'alert alert-danger', role: 'alert')) if !@pokemon_battle.errors.include?(:pokemon1_id).blank? %></li>
				</ul>
			</td>
		</tr>
	</table>
	<% end %>
</div>
<div class="col-sm-6" id="pokemon2">
	<h1>
	<% if @pokemon_battle.pokemon_winner_id == @pokemon2.id and @pokemon_battle.state == "Finished" %>
		<kbd><%= "WINNER" %></kbd>
	<% elsif @pokemon_battle.state == "Finished" %>
		<kbd><%= "LOSER" %></kbd>
	<% end %>
	</h1>
	<pre>Pokemon 2</pre>
	<%= image_tag @pokemon2.pokedex_image, size: "300x300" %>
	<br /><br />
	<table class="table table-bordered">
		<tr>
			<td width="50%">Name</td>
			<th><%= @pokemon2.name %></th>
		</tr>
		<tr>
			<td>HP</td>
			<th><%= @pokemon2.current_health_point %>
				/
				<%= @pokemon2.max_health_point %>
			</th>
		</tr>
	</table>

	<% unless @pokemon_battle.state == "Finished" %>
	<% if @pokemon_battle.battle_type == "Me vs Me" %>
		<table class="table table-bordered">
			<tr>
				<td>Skills</td>
				<th>
					<%= form_tag(pokemon_battle_attack_path(@pokemon_battle), method: 'post') do %>
						<select class="form-control form-group" name="skill_id">
							<% @pokemon2.pokemon_skills.each do |pokemon_skill| %>
								<option value="<%= pokemon_skill.id %>">
									<%= "#{pokemon_skill.skill_name} (#{pokemon_skill.current_pp}/#{pokemon_skill.skill_max_pp})" %>
									</option>
							<% end %>
						</select>
						<input type="hidden" name="attacker_id" value="<%= @pokemon2.id %>">
				</th>
			</tr>
			<tr>
				<td colspan="2">
					<ul class="list-inline">
						<li><%= submit_tag "Attack", class: 'btn btn-danger' %></li>
						<% end %>
						<li>
							<%= form_tag(pokemon_battle_surrender_path(@pokemon_battle), method: 'post') do %>
							<%= submit_tag "Surrender", class: 'btn btn-warning' %>
							<input type="hidden" name="surrender_id" value="<%= @pokemon2.id %>">
							<% end %>
						</li>
						<li><%= (content_tag(:div, @pokemon_battle.errors.full_messages_for(:pokemon2_id).to_sentence , class: 'alert alert-danger', role: 'alert')) if !@pokemon_battle.errors.include?(:pokemon2_id).blank? %></li>
					</ul>
				</td>
			</tr>
		</table>
	<% else %>
		<table class="table table-bordered">
		<tr>
			<td>Skills</td>
			<th>
				<%= form_tag(pokemon_battle_attack_path(@pokemon_battle), method: 'post') do %>
					<select class="form-control form-group" disabled="disabled" name="skill_id">
						<% @pokemon2.pokemon_skills.each do |pokemon_skill| %>
							<option value="<%= pokemon_skill.id %>">
								<%= "#{pokemon_skill.skill_name} (#{pokemon_skill.current_pp}/#{pokemon_skill.skill_max_pp})" %>
								</option>
						<% end %>
					</select>
					<input type="hidden" name="attacker_id" value="<%= @pokemon2.id %>">
			</th>
		</tr>
		<tr>
			<td colspan="2">
				<ul class="list-inline">
					<li><%= submit_tag "Attack", disabled: 'disabled', class: 'btn btn-danger' %></li>
					<% end %>
					<li>
						<%= form_tag(pokemon_battle_surrender_path(@pokemon_battle), method: 'post') do %>
						<%= submit_tag "Surrender", disabled: 'disabled', class: 'btn btn-warning' %>
						<input type="hidden" name="surrender_id" value="<%= @pokemon2.id %>">
						<% end %>
					</li>
					<li><%= (content_tag(:div, @pokemon_battle.errors.full_messages_for(:pokemon2_id).to_sentence , class: 'alert alert-danger', role: 'alert')) if !@pokemon_battle.errors.include?(:pokemon2_id).blank? %></li>
				</ul>
			</td>
		</tr>
	</table>
	<% end %>	
	<% end %>
</div>

<div class="col-sm-12">
	<table class="table table-bordered">
		<thead class="bg-primary">
			<tr>
				<th>#</th>
				<th>Battle ID</th>
				<th>Attacker</th>
				<th>Defender</th>
				<th>Skill Name</th>
				<th>Turn</th>
				<th>Damage</th>
				<th>Attacker HP</th>
				<th>Defender HP</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% if !@pokemon_battle_logs.nil? %>
				<% idx = @pokemon_battle_logs.count + 1 %>
				<% pokemon_battle_logs = @pokemon_battle_logs.reverse %>
				<% pokemon_battle_logs.each do |pokemon_battle_log| %>
					<tr>
						<td><%= idx-=1 %></td>
						<td><%= pokemon_battle_log.pokemon_battle_id %></td>
						<td><%= pokemon_battle_log.attacker_name %></td>
						<td><%= pokemon_battle_log.defender_name %></td>
						<td><%= pokemon_battle_log.skill_name if !pokemon_battle_log.skill_id.nil? %></td>
						<td><%= pokemon_battle_log.turn %></td>
						<td><%= pokemon_battle_log.damage %></td>
						<td><%= pokemon_battle_log.attacker_current_health_point %></td>
						<td><%= pokemon_battle_log.defender_current_health_point %></td>
						<td><%= pokemon_battle_log.action_type %></td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
</div>