config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pokedexes
  resources :skills
  resources :pokemons do
    post 'heal'
    get 'heal_all', on: :collection
  	resources :pokemon_skills
  end
  resources :pokemon_battles do
    resources :pokemon_battle_logs
    get 'auto_battle'
  	post 'attack'
  	post 'surrender'
  end
  root 'pages#home'
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
	belongs_to :pokedex
	has_many :pokemon_skills, dependent: :destroy
	has_many :skills, through: :pokemon_skills
	has_many :pokemon_battles1, foreign_key: :pokemon1_id, class_name: 'PokemonBattle', dependent: :destroy
	has_many :pokemon_battles2, foreign_key: :pokemon2_id, class_name: 'PokemonBattle', dependent: :destroy
	validates :name, 
		presence: true,
		uniqueness: true
	validates :level, 
		presence: true,
		numericality: {only_integer: true, greater_than: 0}
	validates :max_health_point, 
		presence: true,
		numericality: {only_integer: true, greater_than: 0}
	validates :current_health_point, 
		presence: true, 
		numericality: {only_integer: true,	greater_than_or_equal_to: 0, less_than_or_equal_to: :max_health_point}
	validates :attack, 
		presence: true,
		numericality: {only_integer: true, greater_than: 0}
	validates :defence, 
		presence: true,
		numericality: {only_integer: true,	greater_than: 0}
	validates :speed, 
		presence: true,
		numericality: {only_integer: true,	greater_than: 0}
	validates :current_experience, 
		presence: true,
		numericality: {only_integer: true,	greater_than_or_equal_to: 0}

	def pokedex_image
		pokedex.image_url
	end

	def pokemon_battles
		self.pokemon_battles1 + self.pokemon_battles2
	end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

	def index
		@pokemons = Pokemon.all
		navigation_add("Pokemon Index", "#")
	end

	def new
		@pokemon = Pokemon.new
		
		list_pokedexes = Pokedex.all
		@list_names_ids = list_pokedexes.map { |poke| [poke.name, poke.id]}
		navigation_add("Pokemon Index", pokemons_path)
		navigation_add("Pokemon New", "#")
	end

	def create
		@pokemon = Pokemon.new(new_pokemon_params)
		set_pokemon_attr
		if @pokemon.valid?
			@pokemon.save
			redirect_to pokemon_path @pokemon
		else
			list_pokedexes = Pokedex.all
			@list_names_ids = list_pokedexes.map { |poke| [poke.name, poke.id]}
			render 'new'
		end
	end

	def show
		@pokemon = Pokemon.find(params[:id])
		@pokedex = Pokedex.find(@pokemon.pokedex_id)

		@pokemon_skills = @pokemon.pokemon_skills
		@pokemon_skill = PokemonSkill.new
		@pokemon_skill.pokemon_id = @pokemon.id
		list_skill = Skill.all
		@list_names_ids = list_skill.map { |sk| [sk.name, sk.id] }

		pokemon_show_award = PokemonShowAward.new(
			pokemon: @pokemon)
		@pokemon_stats = pokemon_show_award.pokemon_stats
		
		navigation_add("Pokemon Index", pokemons_path)
		navigation_add("Pokemon Show", "#")
	end

	def edit
		@pokemon = Pokemon.find(params[:id])
		@pokedex = Pokedex.find(@pokemon.pokedex_id)
		navigation_add("Pokemon Index", pokemons_path)
		navigation_add("Pokemon Show", pokemon_path(@pokemon))
		navigation_add("Pokemon Edit", "#")
	end

	def update
		@pokemon = Pokemon.find(params[:id])
		if @pokemon.update_attributes(edit_pokemon_params)
			redirect_to @pokemon
		else
			@pokedex = Pokedex.find(@pokemon.pokedex_id)
			render 'edit'
		end
	end

	def destroy
		@pokemon = Pokemon.find(params[:id])
		@pokemon.destroy
		redirect_to pokemons_path
	end

	def heal
		@pokemon = Pokemon.find(params[:pokemon_id])
		flag = true
		
		@pokemon.pokemon_battles.each do |pokemon_battle|
			flag = false if pokemon_battle.state == "Ongoing"
		end

		if flag
			@pokemon.current_health_point = @pokemon.max_health_point
			@pokemon.pokemon_skills.each do |pokemon_skill| 
				pokemon_skill.current_pp = pokemon_skill.skill_max_pp
				pokemon_skill.save
			end
			@pokemon.save
			redirect_to @pokemon
		else
			flash[:danger] = "Cannot heal"
			@pokemons = Pokemon.all
			render 'index'
		end
	end

	def heal_all
		@pokemons = Pokemon.all
		cant_be_healed = []
		@pokemons.each do |pokemon|
			flag = true
			result = pokemon.pokemon_battles1.where(state: 'Ongoing') + pokemon.pokemon_battles2.where(state: 'Ongoing')
			if result.blank?
				pokemon.current_health_point = pokemon.max_health_point
				pokemon.pokemon_skills.each do |pokemon_skill| 
					pokemon_skill.current_pp = pokemon_skill.skill_max_pp
					pokemon_skill.save
				end
				pokemon.save
			else
				cant_be_healed << pokemon.name
			end
		end
		flash[:danger] = "#{cant_be_healed.to_sentence} can't be healed" if cant_be_healed.count > 0
		@pokemons = Pokemon.all
		render 'index'
	end

	private
	def new_pokemon_params
		params.require(:pokemon).permit(
			:pokedex_id,
			:name
			)
	end

	def edit_pokemon_params
		params.require(:pokemon).permit(
			:pokedex_id,
			:name,
			:level,
			:max_health_point,
			:current_health_point,
			:attack,
			:defence,
			:speed,
			:current_experience
			)
	end

	def set_pokemon_attr
		pokedex = Pokedex.find(@pokemon.pokedex_id)
		@pokemon.level = 1
		@pokemon.max_health_point = pokedex.base_health_point
		@pokemon.current_health_point = pokedex.base_health_point
		@pokemon.attack = pokedex.base_attack
		@pokemon.defence = pokedex.base_defence
		@pokemon.speed = pokedex.base_speed
		@pokemon.current_experience = 0
	end

end

app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
	<%= f.label 'Name', for: 'name' %>
	<%= f.text_field :name, class: 'form-control form-group' %>
	<%= (content_tag(:div, @pokemon.errors.full_messages_for(:name).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon.errors.include?(:name) %>
	<%= f.label 'Pokedex', for: 'pokedex_id' %>
	<%= f.select(:pokedex_id, @list_names_ids, {}, class: 'form-control form-group') %>
	<%= f.submit 'Create', class: 'btn btn-primary form-group' %>
<% end %>

app/views/pokemons/edit.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>Edit Pokemon</h1>
	</div>
<% end %>

<div class="col-sm-4">
	<%= image_tag @pokedex.image_url, size: "200x200" %>
</div>

<div class="col-sm-8">
	<%= form_for @pokemon do |f| %>
		<%= f.label 'Name', for: 'name' %>
		<%= f.text_field :name, class: 'form-control form-group'%>

		<%= (content_tag(:div, @pokemon.errors.full_messages_for(:name).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon.errors.include?(:name) %>

		<%= f.label 'Level', for: 'level' %>
		<%= f.number_field :level, class: 'form-control form-group'%>

		<%= (content_tag(:div, @pokemon.errors.full_messages_for(:level).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon.errors.include?(:level) %>

		<%= f.label "Max Health Point", for: 'max_health_point' %>
		<%= f.number_field :max_health_point, class: 'form-control form-group'%>

		<%= (content_tag(:div, @pokemon.errors.full_messages_for(:max_health_point).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon.errors.include?(:max_health_point) %>

		<%= f.label 'Current Health Point', for: 'current_health_point' %>
		<%= f.number_field :current_health_point, class: 'form-control form-group'%>

		<%= (content_tag(:div, @pokemon.errors.full_messages_for(:current_health_point).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon.errors.include?(:current_health_point) %>

		<%= f.label 'Attack', for: 'attack' %>
		<%= f.number_field :attack, class: 'form-control form-group'%>

		<%= (content_tag(:div, @pokemon.errors.full_messages_for(:attack).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon.errors.include?(:attack) %>

		<%= f.label 'Defence', for: 'defence' %>
		<%= f.number_field :defence, class: 'form-control form-group'%>

		<%= (content_tag(:div, @pokemon.errors.full_messages_for(:defence).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon.errors.include?(:defence) %>

		<%= f.label 'Speed', for: 'speed' %>
		<%= f.number_field :speed, class: 'form-control form-group'%>

		<%= (content_tag(:div, @pokemon.errors.full_messages_for(:speed).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon.errors.include?(:speed) %>

		<%= f.label 'Current Experience', for: 'current_experience' %>
		<%= f.number_field :current_experience, class: 'form-control form-group'%>

		<%= (content_tag(:div, @pokemon.errors.full_messages_for(:current_experience).to_sentence , class: 'alert alert-danger', role: 'alert')) if @pokemon.errors.include?(:current_experience) %>

		<%= f.submit 'Submit', class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/pokemons/index.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>Pokemon</h1>
	</div>
<% end %>

<div class="col-sm-12">
<ul class="list-inline">
	<li><%= link_to '+ New Pokemon', new_pokemon_path, class: "btn btn-primary"%></li>
	<li><%= link_to 'Heal All', heal_all_pokemons_path, class: 'btn btn-success' %></li>
</ul>
	<% flash.each do |key, value| %>
	  <%= content_tag :div, value, class: "alert alert-#{key}" %>
	<% end %>
	<table class="table table-bordered">
		<thead>
		  <tr class="grass">
		    <th>#</th>
		    <th>Name</th>
		    <th>Pokedex ID</th>
		    <th>Level</th>
		    <th>Max Health Point</th>
		    <th>Current Health Point</th>
		    <th>Attack</th>
		    <th>Defence</th>
		    <th>Speed</th>
		    <th>Current Experience</th>
		    <th colspan="2">Action</th>
		  </tr>
		</thead>
		<tbody>
			<% idx=0 %>
			<% pokemon_reverse = @pokemons.reverse %>
			<%  pokemon_reverse.each do |pokemon| %>
				<tr>
					<th><%= idx+=1 %></th>
					<td><%= link_to pokemon.name, pokemon %></td>
					<td><%= pokemon.pokedex_id %></td>
					<td><%= pokemon.level %></td>
					<td><%= pokemon.max_health_point %></td>
					<td><%= pokemon.current_health_point %></td>
					<td><%= pokemon.attack %></td>
					<td><%= pokemon.defence %></td>
					<td><%= pokemon.speed %></td>
					<td><%= pokemon.current_experience %></td>
					<td><%= button_to 'Heal', pokemon_heal_path(pokemon_id: pokemon.id), class: 'btn btn-success' %></td>
					<td><center>
						<%= button_to 'Destroy', pokemon, 
						method: :delete,
						class: 'btn btn-danger',
					  data: { confirm: 'Are you sure?' } %>  	
				  </center></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/pokemons/new.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>New Pokemon</h1>
	</div>
<% end %>

<div class="col-sm-12">
	<h2>Select Pokedex</h2>
	<%= render 'form' %>
</div>

app/views/pokemons/show.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron center-block well">
		<h1>Pokemon Show</h1>
	</div>
<% end %>

<div class="col-sm-12">
	<ul class="list-inline">
		<li><%= button_to 'Heal', pokemon_heal_path(pokemon_id: @pokemon.id), class: 'btn btn-success' %></li>
		<li><%= link_to 'Edit', edit_pokemon_path(@pokemon), class: 'btn btn-primary' %></li>
		<li><%= button_to 'Delete', @pokemon, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %></li>
	</ul>
</div>

<div class="col-sm-4">
	<%= image_tag @pokemon.pokedex_image, size: "200x200" %>
</div>

<div class="col-sm-8">
	<table class="table table-inverse well" style="text-align: center;">
		<tr>
			<td class="bg-primary" width="30%">#</td>
			<td><%= @pokemon.id %></td>
		</tr>
		<tr>
			<td class="bg-primary">Name</td>
			<td><%= @pokemon.name %></td>
		</tr>
		<tr>
			<td class="bg-primary">Level</td>
			<td><%= @pokemon.level %></td>
		</tr>
		<tr>
			<td class="bg-primary">Max Health Point</td>
			<td><%= @pokemon.max_health_point %></td>
		</tr>
		<tr>
			<td class="bg-primary">Current Health Point</td>
			<td><%= @pokemon.current_health_point %></td>
		</tr>
		<tr>
			<td class="bg-primary">Attack</td>
			<td><%= @pokemon.attack %></td>
		</tr>
		<tr>
			<td class="bg-primary">Defence</td>
			<td><%= @pokemon.defence %></td>
		</tr>
		<tr>
			<td class="bg-primary">Speed</td>
			<td><%= @pokemon.speed %></td>
		</tr>
		<tr>
			<td class="bg-primary">Current Experience</td>
			<td><%= @pokemon.current_experience %></td>
		</tr>
		<tr>
			<td class="bg-primary">Number of Battles</td>
			<td><%= @pokemon_stats[:battles] %></td>
		</tr>
		<tr>
			<td class="bg-primary">Number of Wins</td>
			<td><%= @pokemon_stats[:wins] %></td>
		</tr>
		<tr>
			<td class="bg-primary">Percentage Wins</td>
			<td><%= number_to_human(@pokemon_stats[:winning]) if !@pokemon_stats[:winning].nan? %>% </td>
		</tr>
		<tr>
			<td class="bg-primary">Number of Loss</td>
			<td><%= @pokemon_stats[:loss] %></td>
		</tr>
		<tr>
			<td class="bg-primary">Percentage Loss</td>
			<td><%= number_to_human(@pokemon_stats[:losing]) if !@pokemon_stats[:losing].nan? %>% </td>
		</tr>
		<tr>	
			<td class="bg-primary">Most used skill</td>
			<td>
				<table class="table table-bordered">
					<tr class="grass-title">
						<td>Skill Name</td>
						<td>Times used</td>
					</tr>
					<% @pokemon_stats[:skill].each do |skill| %>
					<tr>
						<td><%= skill[:skill].skill_name %></td>
						<td><%= skill[:count] %></td>
					</tr>
					<% end %>
				</table>
			</td>
		</tr>
	</table>
</div>

<br /><br />

<div class="col-sm-12">
<h2>Skills</h2>
<table class="table table-inverse well">
	<thead>
		<tr class="bg-primary">
			<td>Name</td>
			<td>Power</td>
			<td>Current PP</td>
			<td>Element Type</td>
			<td>Action</td>
		</tr>
	</thead>
	<tbody>
		<% @pokemon_skills.each do |skill| %>
			<tr>
				<td><%= skill.skill_name %></td>
				<td><%= skill.skill_power %></td>
				<td><%= skill.current_pp %></td>
				<td><%= skill.skill_element_type %></td>
				<td><%= button_to '✕', pokemon_pokemon_skill_path(pokemon_id: @pokemon.id, id: skill.id) , method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

	<%= form_for([@pokemon, @pokemon_skill]) do |f| %>
		<%= f.label 'Skill', for: 'skill_id' %>
		<%= f.select(:skill_id, @list_names_ids, {}, class: 'form-control form-group') %>
		<%= (content_tag(:div, @pokemon_skill.errors.full_messages.to_sentence , class: 'alert alert-danger', role: 'alert')) unless @pokemon_skill.errors.empty? %>
		<%= f.submit 'Add a skill', class: 'btn btn-info' %>
	<% end %>
</div>